# Generated by Django 2.2.6 on 2019-10-30 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, unique=True), blank=True, null=True, size=None),
        ),
    ]
