# Generated by Django 2.2.6 on 2019-10-30 14:06

from django.db import migrations


def from_name_to_names(apps, schema_editor):
    Drug = apps.get_model('med_list', 'Drug')

    for drug in Drug.objects.all():
        drug.names = [drug.name]
        drug.save()


def back(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('med_list', '0002_drug_names'),
    ]

    operations = [
        migrations.RunPython(from_name_to_names, back),
        migrations.RemoveField(
            model_name='drug',
            name='name',
        ),
    ]
